

export const config = {
    DATABASE_URL:process.env.DATABASE_URL!,
    NODE_ENV:process.env.NODE_ENV!,
    ACCESS_TOKEN_SECRET:process.env.ACCESS_TOKEN_SECRET!,
    ACCESS_TOKEN_EXPIRY:process.env.ACCESS_TOKEN_EXPIRY!,
    REFRESH_TOKEN_SECRET:process.env.REFRESH_TOKEN_SECRET!,
    REFRESH_TOKEN_EXPIRY:process.env.REFRESH_TOKEN_EXPIRY!,
    JWT_ISSUER:process.env.JWT_ISSUER!,
    JWT_AUDIENCE:process.env.JWT_AUDIENCE!,
    DEFAULT_RESPONSE_LIMIT:process.env.DEFAULT_RESPONSE_LIMIT!,
    DEFAULT_RESPONSE_OFFSET:process.env.DEFAULT_RESPONSE_OFFSET!,
}