name: Next.js CI/CD

on: 
    push:
        branches: [main]
    pull_request:
        branches: [main]

env:
  NODE_ENV: test
  NEXT_TELEMETRY_DISABLED: 1


jobs: 
  validate: 
    runs-on: ubuntu-latest
    steps: 
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'
          cache: 'npm'

      - name: Install dependencies
        run: npm ci

      - name: Generate Prisma Client
        run: npx prisma generate

      - name: Check code formatting
        run: npm run format:check
        continue-on-error: true # Optional: won't fail the build but will report issues

      - name: Lint code
        run: |
          npm run lint:fix
          npm run lint
        continue-on-error: false # Will fail the build if there are linting errors

      - name: Type check
        run: npm run type-check

      - name: Build application
        run: npm run build:ci
      - name: Cache Next.js build
        uses: actions/cache@v3
        with:
          path: |
            .next/cache
          key: ${{ runner.os }}-nextjs-${{ hashFiles('**.[jt]s', '**.[jt]sx') }}
          restore-keys: |
            ${{ runner.os }}-nextjs-

